FROM alpine:3.8

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
    rm -r /root/.cache

RUN python3 -m pip install --user --no-cache-dir -r requirements.txt

COPY . web

WORKDIR /usr/src/app/web

CMD ["python", "main.py"]
